

export enum MultimediaErrorTypes {
    NSFW = 'NSFW',
    CONTENT_POLICY_VIOLATION = 'CONTENT_POLICY_VIOLATION',
    OUT_OF_MEMORY = 'OUT_OF_MEMORY',
    TIMEOUT = 'TIMEOUT',
    PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
    FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
    PREDICTION_FAILED = 'PREDICTION_FAILED',
    MISSING_OUTPUT = 'MISSING_OUTPUT',
    INVALID_INPUT = 'INVALID_INPUT'
}



export enum ReplicateErrorCode {
  UNKNOWN_ERROR = 'E1000',
  OUT_OF_MEMORY = 'E1001',
  WEBHOOK_URL_EMPTY = 'E4875',
  TIMEOUT_STARTING = 'E6716',
  STOPPED_NON_TERMINAL = 'E8367',
  HEALTH_CHECK_FAILED = 'E8765',
  ERROR_STARTING = 'E9243',
  UPLOAD_FAILED = 'E9825',
}

export enum ErrorPlatformMokka{
  ELEVENLABS_ERROR='ELEVENLABS_ERROR',
  MOKKA_ERROR='MOKKA_ERROR',
  REPLICATE_ERROR='REPLICATE_ERROR',
  UNKNOWN_ERROR='UNKNOWN_ERROR',
  FILE_SIZE_ERROR='FILE_SIZE_ERROR',
  DATABASE_FAILED='DATABASE_FILED',
  DOWNLOAD_TIMEOUT_ERROR='DOWNLOAD_TIMEOUT_ERROR',
  HTTP_ERROR='HTTP_ERROR',
  DOWNLOAD_ERROR='DOWNLOAD_ERROR',
  OPENAI_ERROR = 'OPENAI_ERROR',
  GOOGLE_UNAUTHORIZED='UNAUTHORIZED',
  GOOGLE_FAILED='GOOGLE_FAILED'
}


export enum OpenAIErrorCode {
    CONTENT_POLICY_VIOLATION = 'content_policy_violation',
    CONTEXT_LENGTH_EXCEEDED = 'context_length_exceeded',
    RATE_LIMIT_EXCEEDED = 'rate_limit_exceeded',
    INSUFFICIENT_QUOTA = 'insufficient_quota',
    INVALID_API_KEY = 'invalid_api_key',
    INVALID_REQUEST = 'invalid_request_error',
    SERVER_ERROR = 'server_error',
}

export enum OpenAIErrorTypes {
    NSFW = 'NSFW_CONTENT',
    CONTEXT_TOO_LONG = 'CONTEXT_TOO_LONG',
    RATE_LIMIT = 'RATE_LIMIT',
    QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_INPUT = 'INVALID_INPUT',
    SERVER_ERROR = 'SERVER_ERROR',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
