export enum ModelsAudio {
  Aria = 'Aria',
  Roger = 'Roger',
  Sarah = 'Sarah',
  Laura = 'Laura',
  Charlie = 'Charlie',
  George = 'George',
  Callum = 'Callum',
  River = 'River',
  Liam = 'Liam',
  Charlotte = 'Charlotte',
  Alice = 'Alice',
  Matilda = 'Matilda',
  Will = 'Will',
  Jessica = 'Jessica',
  Eric = 'Eric',
  Chris = 'Chris',
  Brian = 'Brian',
  Daniel = 'Daniel',
  Lily = 'Lily',
  Bill = 'Bill',
}



export enum IdModelsAudio {
  Aria = '9BWtsMINqrJLrRacOk9x',
  Roger = 'CwhRBWXzGAHq8TQ4Fs17',
  Sarah = 'EXAVITQu4vr4xnSDxMaL',
  Laura = 'FGY2WhTYpPnrIDTdsKH5',
  Charlie = 'IKne3meq5aSn9XLyUdCD',
  George = 'JBFqnCBsd6RMkjVDRZzb',
  Callum = 'N2lVS1w4EtoT3dr4eOWO',
  River = 'SAz9YHcvj6GT2YYXdXww',
  Liam = 'TX3LPaxmHKxFdv7VOQHJ',
  Charlotte = 'XB0fDUnXU5powFXDhCwa',
  Alice = 'Xb7hH8MSUJpSbSDYk0k2',
  Matilda = 'XrExE9yKIg1WjnnlVkGX',
  Will = 'bIHbv24MWmeRgasZH58o',
  Jessica = 'cgSgspJ2msm6clMCkdW9',
  Eric = 'cjVigY5qzO86Huf0OWal',
  Chris = 'iP95p4xoKVk53GoZ742B',
  Brian = 'nPczCjzI2devNBz1zQrb',
  Daniel = 'onwK4e9ZLuTAKqWW03F9',
  Lily = 'pFZP5JQG7iQjIQuC4Bku',
  Bill = 'pqHfZKP75CvOlQylNhV4',
}